main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phonebook.urls'))
]

phonebook/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from . import views

app_name = 'phonebook'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('region-list/', views.getRegionList, name='region-list'),
    path('user-info/', views.getUserInfo, name='user-info'),
    path('edit-user-info-form/', views.getUserInfo, name='edit-user-info-form'),
    path('edit-user-info', views.editUserInfo, name='edit-user-info'),
    path('favorite-list/', views.getFavoriteList, name='favorite-list'),
    path('add-favorite/', views.addFavorite, name='add-favorite'),
    path('remove-favorite/', views.removeFavorite, name='remove-favorite'),
    path('<int:pk>/', views.RegionView.as_view(), name='region'),
    path('<int:pk>/login/', views.login, name='login'),
    path('<int:pk>/logout/', views.logout, name='logout'),
    path('search-all/', views.searchAll, name='search-all'),
    re_path(r'^(?P<pk>[0-9]+)/search/$', views.search, name='search'),
    #re_path(r'^search/$<str:search>', views.SeachView.as_view, name='search')
]

untitled/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

phonebook/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib import auth

from main import settings

# Должность сотрудника
class Position(models.Model):
    position_name = models.CharField(max_length=200)

    def __str__(self):
        return self.position_name


''' В каком отделе филиала сотрудник работает (например, сотрудник числится в филиале Приморского края и работает
в отделе подготовки кадров) '''
class Department(models.Model):
    department_name = models.CharField(max_length=200)

    def __str__(self):
        return self.department_name


# Город
class City(models.Model):
    city_name = models.CharField(max_length=200)
    timezone = models.IntegerField(null=True, default=None)

    def __str__(self):
        return self.city_name


# В каком филиале сотрудник числится
class Region(models.Model):
    region_name = models.CharField(max_length=200)
    city_id = models.ForeignKey(City, on_delete=models.PROTECT, null=True, default=None)

    def __str__(self):
        return self.region_name

# Информация о самом сотруднике
class Person(models.Model):
    auth_user = models.ForeignKey(User, null=True, default=None, on_delete=models.DO_NOTHING)
    full_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, null=True, default=None)
    city_phone = models.CharField(max_length=200, null=True, default=None)
    ip_phone = models.CharField(max_length=200, null=True, default=None)
    position = models.ForeignKey(Position, on_delete=models.PROTECT, null=True, default=None)
    department = models.ForeignKey(Department, on_delete=models.PROTECT, null=True, default=None)
    region = models.ForeignKey(Region, on_delete=models.PROTECT, null=True, default=None)
    room = models.CharField(max_length=200, null=True, default=None)

    def __str__(self):
        return self.full_name

# Избранные номера для каждого сотрудника (работают только в том случае, если пользователь залогинился)
class Favorite(models.Model):
    user = models.ForeignKey(User, null=True, default=None, on_delete=models.CASCADE)
    favorite_number = models.ForeignKey(Person, null=True, default=None, on_delete=models.CASCADE)

phonebook/forms.py
from django import forms


# Форма поиска (просто строка с текстом)
class SearchForm(forms.Form):
    q = forms.CharField(required=False, label="", max_length=100,
                        widget=forms.TextInput(attrs={'class' : 'form-control mr-sm-2','placeholder': 'Найти',
                                                      'data-toggle':'tooltip', 'title': 'Поиск осуществляется по всем '
                                                                                        'выводимым полям в таблице'}))

    def clean_q(self):
        #Если нажата кнопка "Очистки", то возвращаем ложь, иначе, если нажата кнопка поиска, возвращаем истину
        if 'clear' in self.data:
            return 'clear'
        elif 'search' in self.data:
            data = self.cleaned_data['q'].strip()
            if not data:
                return 'clear'
            else:
                return 'search'

phonebook/views.py
import operator
from functools import reduce

from django.db.models import Q
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.template.context_processors import csrf
from django.urls import reverse, resolve
from django.views import generic, View
from django.http import HttpResponse, request, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib import auth

from phonebook.forms import SearchForm
from .models import Person, Department, Region, Favorite, Position
from django.contrib.postgres.search import SearchVector
import numpy as np

''' Класс общих представлений generic views, который берёт из базы данных данные и вставляет нам в HTML страницу '''

'''     Здесь планировалось использовать фреймворки Haystrack и Whoosh для поиска нескольких строк таблицы или таблиц 
    по БД, но Haystrack (считай обёртка) уж больно кривой и к тому же он явно заточен под старую версию Django. 
    Тем более, в случае с БД Postrgresql, уже существует нормальная реализация поиска в самой БД, поэтому особого смысла
    встраивать левый фреймворк для поиска по бд нет '''

'''     Данный класс ListView используется для отображения информации, которая берётся из БД, возвращая переменные 
    (или же контекст person_list, department, form, region), 
    которые вставляются в HTML шаблон (например: kadastr/phonebook). 
    Он рендерит страницу региона ЦА ФГБУ '''
class IndexView(generic.ListView):
    template_name = 'phonebook/phonebook.html'
    context_object_name = 'person_list'

    # Возвращает список работников
    def get_queryset(self):
        return Person.objects.all().filter(region_id=3)

    # Возвращает список переменных (контекстов) для вставки в HTML шаблон
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['department_list'] = Department.objects.all().order_by('id').filter(
            reduce(operator.or_, (Q(department_name__contains=x[0])
                                  for x in context['person_list'].values_list('department__department_name').exclude(
                department__isnull=True))))
        context['form'] = SearchForm(initial={'search': "", })
        context['region'] = Region.objects.all().filter(id=3)
        context['user'] = auth.get_user(self.request)
        return context


    ''' Данный класс возвращает сотрудников данного выбранного региона. Преобразует URL адрес, исходя из выбранного региона 
    (например: kadastr/phonebook/1), возвращая переменные (person_list, department, form, region), 
    которые вставляются в HTML шаблон '''
class RegionView(generic.ListView):
    template_name = 'phonebook/phonebook.html'
    context_object_name = 'person_list'

    def get_queryset(self):
        return Person.objects.all().filter(region_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(RegionView, self).get_context_data(**kwargs)
        if context['person_list']:
            context['department_list'] = Department.objects.all().order_by('id').filter(
                reduce(operator.or_, (Q(department_name__contains=x[0])
                                      for x in
                                      context['person_list'].values_list('department__department_name').exclude(
                                          department__isnull=True))))
        context['form'] = SearchForm(initial={'search': "", })
        context['region'] = Region.objects.all().filter(id=self.kwargs['pk'])
        context['user'] = auth.get_user(self.request)
        return context


    '''     Данная функция используется для фильтрации сотрудников по таким критериям: Полное имя, городской телефон,
    ip телефон, должность. Также преобразует URL адрес, исходя из запроса или вбитых данных в форму 
    (например kadastr/phonebook/1/search/q=danil), возвращая переменные (person_list, department, form, region), 
     которые вставляются в HTML шаблон'''
def search(request, pk):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            region = Region.objects.all().filter(id=pk)
            user = auth.get_user(request)
            if form.cleaned_data['q'] == 'search':  # Если запрос не пустой, то мы возвращаем фильтрованный список работников
                filtered_persons = Person.objects.annotate(
                    search=SearchVector('full_name', 'city_phone', 'ip_phone', 'position__position_name')) \
                    .filter(search=request.GET['q']).filter(region_id=pk)
                if filtered_persons:
                    filtered_departments = Department.objects. \
                        filter(reduce(operator.or_, (Q(department_name__contains=x[0])
                                                     for x in
                                                     filtered_persons.values_list('department__department_name').
                                      exclude(department__isnull=True))))
                else:
                    filtered_departments = None
                return render(request, 'phonebook/phonebook.html',
                              {'person_list': filtered_persons,
                               'department_list': filtered_departments,
                               'form': form,
                               'region': region,
                               'user': user})
            elif form.cleaned_data['q'] == 'clear':  # Иначе возвращаем список всех работников
                return HttpResponseRedirect(reverse('phonebook:region', args=str(region[0].id)))


'''     Данная функция используется для фильтрации сотрудников по таким критериям: Полное имя, городской телефон,
    ip телефон, должность. Используется в ajax запросе в модальном окне, 
    возвращая переменные (person_list, department, form, region), которые вставляются в HTML шаблон'''
def searchAll(request):
    filtered_persons = Person.objects.annotate(
        search=SearchVector('full_name', 'city_phone', 'ip_phone', 'position__position_name')) \
        .filter(search=request.GET['q'])
    if filtered_persons:
        filtered_departments = Department.objects. \
            filter(reduce(operator.or_, (Q(department_name__contains=x[0])
                                         for x in
                                         filtered_persons.values_list('department__department_name').
                          exclude(department__isnull=True))))
    else:
        return HttpResponse('По вашему запросу не было найдено ни одного сотрудника')
    return render(request, 'phonebook/searchAll.html',
                  {'person_list': filtered_persons,
                   'department_list': filtered_departments,})


''' Получить список регионов (используется в ajax запросе). Возвращает переменную region_list, которая вставляется в
HTML шаблон в модальное окно '''
def getRegionList(request):
    return render(request, 'phonebook/region.html', {'region_list': Region.objects.all()})

''' Получить информацию о авторизированном пользователе (используется в ajax запросе). 
Возвращает переменные user и user_info, которые вставляются в HTML шаблон в модальное окно '''
def getUserInfo(request):
    user = auth.get_user(request)
    user_info = Person.objects.all().filter(auth_user=user.id)
    if (resolve(request.path_info).url_name == 'user-info'):
        return render(request, 'phonebook/userInfo.html', {'user': user,
                                                       'user_info': user_info})
    elif (resolve(request.path_info).url_name == 'edit-user-info-form'):
        return render(request, 'phonebook/editUserInfo.html', {'user': user,
                                                            'user_info': user_info,
                                                            'position_list': Position.objects.all(),
                                                            'department_list' : Department.objects.all(),
                                                            'region_list' : Region.objects.all()})

''' Изменить информацию о авторизированном пользователе '''
def editUserInfo(request):
    if (request.POST['userFullName'].strip()):
        Person.objects.filter(auth_user=auth.get_user(request).id).update(full_name=request.POST['userFullName'])
        Person.objects.filter(auth_user=auth.get_user(request).id).update(email=request.POST['email'])
        if (request.POST['position_id'] != '0'):
            Person.objects.filter(auth_user=auth.get_user(request).id).update(position_id=request.POST['position_id'])
        else:
            Person.objects.filter(auth_user=auth.get_user(request).id).update(position_id=None)
        Person.objects.filter(auth_user=auth.get_user(request).id).update(city_phone=request.POST['city_phone'])
        Person.objects.filter(auth_user=auth.get_user(request).id).update(ip_phone=request.POST['ip_phone'])
        if (request.POST['department_id'] != '0'):
            Person.objects.filter(auth_user=auth.get_user(request).id).update(department_id=request.POST['department_id'])
        else:
            Person.objects.filter(auth_user=auth.get_user(request).id).update(department_id=None)
        if (request.POST['region_id'] != '0'):
            Person.objects.filter(auth_user=auth.get_user(request).id).update(region_id=request.POST['region_id'])
        else:
            Person.objects.filter(auth_user=auth.get_user(request).id).update(region_id=None)
        return HttpResponse('')
    else:
        return HttpResponse(False)

''' Добавляет номер в избранное. Добавляет в базу данных id пользователя, который зашёл в систему и id пользователя,
чей номер был выбран для добавления в избранное '''
def addFavorite(request):
    Favorite.objects.create(user_id=auth.get_user(request).id, favorite_number_id=request.POST['person_id'])
    return HttpResponse('')

phonebook/templates/phonebook/branch_office.html
{% for entry in entry_list %}
    <a href="{% url 'phonebook:region' entry.id %}">{{ entry }} </a>
    <br/>
{% endfor %}

phonebook/templates/phonebook/editUserInfo.html
 <div class="form-group row">
        <label class="col-sm-4 col-form-label">Полное имя:</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="editUserFullName" value="{{ user_info.0.full_name }}">
            <div class="invalid-feedback">
                Имя не может быть пустым!
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Должность:</label>
        <div class="col-sm-8">
            <select class="selectpicker form-control" id="editUserPosition" data-show-subtext="true" data-live-search="true">
                <option id="0">-</option>
                {% for position in position_list %}
                    <option id="{{ position.id }}">{{ position }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Почта:</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="editUserEmail" value={% if user_info.0.email %}
                    {{ user_info.0.email }}
            {% else %}
                {{ '' }}
            {% endif %}>

        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Городской телефон:</label>
        <div class="col-sm-8">
                <input class="form-control" type="text" id="editUserCityPhone" value={% if user_info.0.city_phone %}
                    {{ user_info.0.city_phone }}
                {% else %}
                    {{ '' }}
                {% endif %}>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">ip-телефон:</label>
        <div class="col-sm-8">
                <input type="text" class="form-control" id="editUserIpPhone" value={% if user_info.0.ip_phone %}
                    {{ user_info.0.ip_phone }}
                {% else %}
                    {{ '' }}
                {% endif %}>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Отдел:</label>
        <div class="col-sm-8">
            <select class="selectpicker form-control" id="editUserDepartment" data-show-subtext="true" data-live-search="true">
                <option id="0">-</option>
                {% for department in department_list %}
                    <option id="{{ department.id }}">{{ department }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Регион:</label>
        <div class="col-sm-8">
            <select class="selectpicker form-control" id="editUserRegion" data-show-subtext="true" data-live-search="true">
                <option id="0">-</option>
                {% for region in region_list %}
                    <option id="{{ region.id }}">{{ region }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-8 col-form-label" id="editUserInformation"></label>
    </div>

phonebook/templates/phonebook/favorite.html
<script>
    $(document).ready(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

<table class="table table-sm table-bordered" id="favorite-table">
  <thead>
    <tr>
      <th scope="col">ФИО</th>
      <th scope="col">Должность</th>
      <th scope="col">E-Mail</th>
      <th scope="col">Городской телефон</th>
      <th scope="col">IP телефон</th>
      <th scope="col">Регион</th>
    </tr>
  </thead>
<tbody>

{% for department in department_list %}
    <tr class="tr-department">
        <th colspan="6" id="department{{ forloop.counter }}"> {{ department }}</th>
    </tr>
    {% for favorite in favorite_list %}
        {% if favorite.favorite_number.department == department %}
        <tr id={{ favorite.favorite_number.id }}>
            <th scope="row">
                {% if user %}
                <a href="#" id={{ favorite.favorite_number.id }}>
                    <i class="fa fa-minus" data-toggle="tooltip" title="Удалить из избранного"></i>
                </a>
                    {% endif %}
                {{ favorite.favorite_number }}
            </th>

            {% if favorite.favorite_number.position %}
                <td>{{ favorite.favorite_number.position }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if favorite.favorite_number.email %}
                <td>{{ favorite.favorite_number.email }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if favorite.favorite_number.city_phone %}
                <td>{{ favorite.favorite_number.city_phone }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if favorite.favorite_number.ip_phone %}
                <td>{{ favorite.favorite_number.ip_phone}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if favorite.favorite_number.region %}
                <td>{{ favorite.favorite_number.region}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}
        </tr>
        {% endif %}
    {% endfor %}
{% endfor %}
</tbody>
</table>

<script>
    $(document).ready(function () {
    /*
        Таблица избранных номеров в всплывающем окне. При нажатии на иконку минуса в таблице, удаляем
        данный номер из избранных
     */
    $('#favorite-table a').click(function () {
        console.log('Clicked list. ' + this.id);
        $.ajax({
            method: 'POST',
            url: '{% url 'phonebook:remove-favorite' %}',
            data: {
                "csrfmiddlewaretoken": "{{csrf_token}}",
                'person_id': this.id
            },
            cache: false,
            success: function (data) {
                $('#favorite-modal-window-content').html(data);
            },
            error: function (data) {
                alert('Ошибка удаления из избранных! Попробуйте перезагрузить страницу');
            }
        });
    });
    });
</script>

phonebook/templates/phonebook/phonebook.html
{% extends "phonebook/wrapper.html" %}

{% block content %}
    <!-- Sidebar -->
     <div class="sidebar" id="sidebar">
    <div class="list-group">
        {% for department in department_list %}
            <a class="list-group-item list-group-item-action" href="#department{{ forloop.counter }}">{{ department }}</a>
        {% endfor %}
    </div>
    </div>

<!-- Page content -->
<div class="content" id="content" data-spy="scroll" data-target="#sidebar" data-offset="0">
<!-- Table -->
<table class="table table-sm table-bordered" id="person-table">
  <thead>
    <tr>
        <th scope="col">ФИО</th>
        <th scope="col">Должность</th>
        <th scope="col">E-Mail</th>
        <th scope="col">Городской телефон</th>
        <th scope="col">IP телефон</th>
        <th scope="col">Кабинет</th>
    </tr>
  </thead>
<tbody>

{% for department in department_list %}
    <tr class="tr-department">
        <th colspan="6" id="department{{ forloop.counter }}"> {{ department }}</th>
    </tr>
    {% for person in person_list %}
        {% if person.department == department %}
        <tr>
            <th scope="row">
                {% if user.is_authenticated %}
                <a href="#" id={{ person.id }}>
                    <i class="fa fa-star-o" data-toggle="tooltip" title="Добавить в избранное"></i>
                </a>
                    {% endif %}
                {{ person }}
            </th>

            {% if person.position %}
                <td>{{ person.position }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.email %}
                <td>{{ person.email }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.city_phone %}
                <td>{{ person.city_phone }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.ip_phone %}
                <td>{{ person.ip_phone}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.room %}
                <td>{{ person.room}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}
        </tr>
        {% endif %}
    {% endfor %}
{% endfor %}
</tbody>
</table>
<button class="btn btn-light scroll-top-button" id="push" style="border-color: lightgrey">
    <i class="fa fa-arrow-up fa-2x" aria-hidden="true"></i>
</button>
</div>
{% endblock %}

phonebook/templates/phonebook/region.html
{% for region in region_list %}
    <a href="{% url 'phonebook:region' region.id %}">{{ region }} </a>
    <br/>
{% endfor %}

phonebook/templates/phonebook/search.html
{% extends "phonebook/wrapper.html" %}

{% block content %}
<table class="table table-sm table-bordered" data-spy="scroll" data-target="#sidebar">
  <thead>
    <tr>
      <th scope="col">ФИО</th>
      <th scope="col">Должность</th>
      <th scope="col">E-Mail</th>
      <th scope="col">Городской телефон</th>
      <th scope="col">IP телефон</th>
    </tr>
  </thead>
<tbody>

    {% for person in person_list %}
        <tr>
            <th scope="row"> {{ person }}</th>

            {% if person.position %}
                <td>{{ person.position }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.email %}
                <td>{{ person.email }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.city_phone %}
                <td>{{ person.city_phone }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.ip_phone %}
                <td>{{ person.ip_phone}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}
        </tr>
    {% endfor %}
</tbody>
</table>
{% endblock %}

phonebook/templates/phonebook/searchAll.html
<table class="table table-sm table-bordered" id="person-table">
  <thead>
    <tr>
        <th scope="col">ФИО</th>
        <th scope="col">Должность</th>
        <th scope="col">E-Mail</th>
        <th scope="col">Городской телефон</th>
        <th scope="col">IP телефон</th>
        <th scope="col">Регион</th>
        <th scope="col">Кабинет</th>
    </tr>
  </thead>
<tbody>

{% for department in department_list %}
    <tr class="tr-department">
        <th colspan="7" id="department{{ forloop.counter }}"> {{ department }}</th>
    </tr>
    {% for person in person_list %}
        {% if person.department == department %}
        <tr>
            <th scope="row">
                {% if user.is_authenticated %}
                <a href="#" id={{ person.id }}>
                    <i class="fa fa-star-o" data-toggle="tooltip" title="Добавить в избранное"></i>
                </a>
                    {% endif %}
                {{ person }}
            </th>

            {% if person.position %}
                <td>{{ person.position }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.email %}
                <td>{{ person.email }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.city_phone %}
                <td>{{ person.city_phone }}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.ip_phone %}
                <td>{{ person.ip_phone}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.department %}
                <td>{{ person.department}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}

            {% if person.room %}
                <td>{{ person.room}}</td>
            {% else %}
                <td>{{ "-" }}</td>
            {% endif %}
        </tr>
        {% endif %}
    {% endfor %}
{% endfor %}
</tbody>
</table>

phonebook/templates/phonebook/userInfo.html
<p> Логин пользователя: {{ user }}</p>
<div class="container">
    <div class="row">
        <div class="col-5">
            Полное имя:
        </div>
        <div class="col">
            {{ user_info.0.full_name }}
        </div>
              </div>
    <div class="row">
        <div class="col-5">
            Должность:
        </div>
        <div class="col">
            {% if user_info.0.position %}
                {{ user_info.0.position }}
            {% else %}
                {{ "-" }}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-5">
            Почта:
        </div>
        <div class="col">
            {% if user_info.0.email %}
                {{ user_info.0.email }}
            {% else %}
                {{ "-" }}
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            Городской телефон:
        </div>
        <div class="col">
            {% if user_info.0.city_phone %}
                {{ user_info.0.city_phone }}
            {% else %}
                {{ "-" }}
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            ip-телефон:
        </div>
        <div class="col">
            {% if user_info.0.ip_phone %}
                {{ user_info.0.ip_phone }}
            {% else %}
                {{ "-" }}
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            Кабинет:
        </div>
        <div class="col">
            {% if user_info.0.room %}
                {{ user_info.0.room }}
            {% else %}
                {{ "-" }}
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            Отдел:
        </div>
        <div class="col">
            {% if user_info.0.department %}
                {{ user_info.0.department }}
            {% else %}
            {{ "-" }}
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-5">
            Регион:
        </div>
        <div class="col">
            {% if user_info.0.region %}
                {{ user_info.0.region }}
            {% else %}
                {{ "-" }}
            {% endif %}
        </div>
    </div>
</div>